# Generated by Django 5.0.2 on 2024-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_categoriaprod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprod',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Niños')], max_length=1),
        ),
    ]
